pact-foundation/pact-mock_service

lib/pact/mock_service/cli.rb

Very simple change to add a --ssl option to the mock_service CLI. Allows it to run with a self-signed certificate.
This is very helpful for testing browser-based consumers.
(redone pull req. from branch)

Added support to run the mock service on SSL. Important for browser-based consumers.

---

README.md
spec/integration/cli_ssl_spec.rb

Continuing on from #4, added integration spec and rudimentary documentation to README.md.

SSL Support: Add documentation to README and add integration spec

---

lib/pact/mock_service.rb

Install on clean server fails 
with /home/andre/.rvm/gems/ruby-2.1.2/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require': cannot load such file -- pact/consumer/app_manager
This fixes it, by using the available app_manager

Fixing path

---

packaging/wrapper.bat

Default pact-dir parameter added to windows wrapper to avoid path incompatibilities.

Default pact-dir for windows mock service included in wrapper.

---

lib/pact/mock_service/request_handlers/interaction_post.rb
spec/lib/pact/mock_service/request_handlers/interaction_post_spec.rb

The third element of a rack return value should respond to `#each`, but in the error scenario it was returning a plain string, rather than an array.
I was getting an error adding one of my interactions, but the error message I saw was:
```
RuntimeError: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
<HEAD><TITLE>Internal Server Error</TITLE></HEAD>
<BODY>
<H1>Internal Server Error</H1>
undefined method `each' for #&lt;String:0x007f8e62ae5b58&gt;
<HR>
<ADDRESS>
WEBrick/1.3.1 (Ruby/2.1.5/2014-11-13) at
localhost:3077
</ADDRESS>
</BODY>
</HTML>
```
with this change, I now see:
```
RuntimeError: An interaction with same description ("PUT new entry") and
provider state ("an empty content register") but a different request
path, response status and response body has already been used. …
```

Produce a valid rack response on interaction post error

---

lib/pact/mock_service/cli.rb
lib/pact/mock_service/run.rb

This allows the mock service to be run on an interface
other than localhost.
We have been using this run the mock service inside a
docker container and be called from a linked
container.

Added a CLI option to alter binding address

---

packaging/wrapper.sh

This will fix https://github.com/bethesque/pact-mock-service-npm/issues/1 for both linux and osx.  The bat file seems to already work with the Windows packaging.
Is it possible to repackage after this so that the latest can be used in node?
Cheers.

fixing wrapper to work with both symlinked and non-symlinked files

---

lib/pact/mock_service/request_handlers.rb
lib/pact/mock_service/request_handlers/session_delete.rb
lib/pact/mock_service/session.rb
spec/features/log/mock_multiple_responses_spec.log
spec/features/log/mock_one_response_spec.log
spec/lib/pact/mock_service/request_handlers/session_delete_spec.rb
spec/lib/pact/mock_service/session_spec.rb

Adds support to clear an entire session to allow
long lived pact mock servers.  This is useful when repeatedly
testing against the same server process
Tests can invoke DELETE /session to flush out all:
- expected interactions
- actual interactions
- verified interactions

Adds DELETE session endpoint

---

README.md

Hi,
You have a great tool here that I nearly ignored and reimplemented due to lack of documentation! :-)
I don't mind if you don't use this change, or if you correct / expand / rewrite it, but please do the poor souls trying to use your lovely software a favour and put in something like this in for us. Also if I've got it wrong please god tell me because it took me ages to piece together it's usage - simple as it is.
I'm not a ruby developer so picking through the source code and trawling google groups for clues was not fun. What I (and people like me) need is simple, vanilla usage examples - hence why I've used curl. You have an example of starting the server but I was like "Great! Now what...?" :-)
I still have no idea what else pact mock service can do!
As a side note, again not being …

Added a README example of using the pack-mock-server as a stub.

---

lib/pact/mock_service/request_handlers/options.rb

We have a bunch of APIs that are using PATCHes rather than PUTs and not having it in the `Access-Control-Allow-Methods` causes pact failures. This is a simplest change ever, but if we want to make it a bit more intelligent and, say, cater for any HTTP verb, or being able to configure which verbs are allowed somehow - I'm happy to do that.

allowing PATCH method in the CORS handler

---

lib/pact/consumer_contract/consumer_contract_writer.rb
spec/lib/pact/consumer_contract/consumer_contract_writer_spec.rb

We don't always need to write pact file. For example, when we have both
local development machine and CI machine, we want to generate only in CI
machine not local development machine.
I want to use this feature by configuring Pact in consumer project's pact_helper like:
```ruby
Pact.configure do |config|
config.pactfile_write_mode = :none unless ENV['RUN_CI']
end
```
How about supporting this feature?

[Proposal] Add option not to write pact file

---

.travis.yml

As same as https://github.com/bethesque/pact-support/pull/16, https://github.com/bethesque/pact-support/pull/17, run CI with new Rubies.

Update Travis CI setting with new Rubies

---

lib/pact/consumer/server.rb
lib/pact/mock_service/app_manager.rb
lib/pact/mock_service/run.rb
spec/lib/pact/consumer/server_spec.rb
spec/lib/pact/mock_service/app_manager_spec.rb

The actual changes are fbea6d4.
The big change is spawn mock servers as soon as configured mock services.
Previously, they were spawned in RSpec's before suite hook.
This is because we have to obtain actual port and return it to caller. The caller is
`Pact::Consumer::Configuration::MockService#register_mock_service` and it
have to set returned port as soon as call `register_mock_service_for`.
Since booting mock servers is not time consumption task in pact-mock_service,
I think this change may be acceptable. I might be able to plan alternatives to
boot mock servers in before suite hook by making more changes to pact gem,
though.
How do you think?
We use [RRRSpec](https://github.com/cookpad/rrrspec) to run RSpec tests heavy concurrently. I tested this patch in that environment and it looks …

`find_available_port` option

---

lib/pact/mock_service/cli.rb
lib/pact/mock_service/control_server/run.rb

This enables to specify 0.0.0.0 as host and enables to reach the mock
server from inside a docker container (see
http://stackoverflow.com/questions/27806631/docker-rails-app-fails-to-be-served-curl-56-recv-failure-connection-reset
).

add host option for control server

---

lib/pact/mock_service/request_handlers/interactions_put.rb

If you set up pact so an `AlmostDuplicateInteractionError` was raised, the webserver would return the following response:
```
[2016-04-18 14:10:25] ERROR NoMethodError: undefined method `each' for #<String:0x007ff1eaa74cc8>
/Users/aaron/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:112:in `service'
/Users/aaron/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:138:in `service'
/Users/aaron/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/webrick-1.3.1/lib/webrick/httpserver.rb:94:in `run'
/Users/aaron/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/webrick-1.3.1/lib/webrick/server.rb:191:in `block in start_thread'
```
This is because `InteractionsPut#respond` was returning an invalid rack response. This change fixes …

Fixed invalid Rack response on AlmostDuplicateInteractionError

---

packaging/wrapper.sh

Fixes the [warning](https://github.com/pact-foundation/pact-mock-service-npm#known-issues) on run:
```
No entry for terminal type "xterm-256color";
using dumb terminal settings.
```
I removed this for https://github.com/pact-foundation/pact-provider-verifier and that seemed to do the trick.

Fix "No entry for terminal..." warning

---

lib/pact/consumer_contract/consumer_contract_decorator.rb
lib/pact/mock_service/version.rb
pact-mock-service.gemspec
spec/features/log/mock_multiple_responses_spec.log
spec/features/log/mock_one_response_spec.log
spec/lib/pact/consumer_contract/consumer_contract_decorator_spec.rb

In order to avoid unnecessary contract file changes. 
Generally RSpec does not execute tests in alphabetical order, it means that if you run the test without any changes several times, it creates pact contract with interactions in random order too.
As a result you need to be careful to understand do you have any changes in pact contract or just commit changes every time it changes the contract.

Order interactions within the contract by provider state.

---

lib/pact/consumer_contract/consumer_contract_writer.rb
spec/features/write_pact_file_spec.rb

We run RSec parallelized on CircleCI. CircleCI divides the spec files among multiple containers, and currently each container's RSpec run generates a contract file. These contract files are stored as build artifacts by CircleCI so that they can be fetched by the providers when they run pact verification.
Currently, if you run RSpec on any specific spec file(s) that do not include a pact spec file, it will generate a contract for that pact anyway, containing no interactions. So in our use case, every container generates a contract file, and only one of them contains interactions. CircleCI then chooses one of the container's artifacts (seemingly at random). This results in pact verification on the provider always passing since there are no interactions that might fail.
You can also …

Write contract file only when there are interactions for it

---

lib/pact/mock_service/cli.rb
lib/pact/mock_service/server/respawn.rb
lib/pact/mock_service/server/spawn.rb
lib/pact/mock_service/server/wait_for_server_up.rb
spec/integration/cli_ssl_spec.rb
spec/support/integration_spec_support.rb

Updated WaitForServerUp to use SSL if mock service was started with --ssl option. Currently it fails after 100 failed http get checks.

use ssl when checking if https server is up

---

tasks/package.rake

Required to upgrade the mock service in NPM land, see https://github.com/pact-foundation/pact-mock-service-npm/issues/17.
Hold off on merging this, it's still untested on Windows and I'm nervous about the caveat on Traveling Ruby's website. This hopefully gets the ball moving though.

Upgrade Traveling Ruby to work with Ruby 2.2.x

---

lib/pact/consumer/server.rb

My use case is hosting my test cases with their `Pact.service_consumer` mock in one of my docker-compose services, bind consumer server to '0.0.0.0' will fix the access between docker-compose services.

bind webrick of consumer server to 0.0.0.0

---

lib/pact/mock_service/request_handlers/options.rb
spec/lib/pact/mock_service/request_handlers/options_spec.rb

Before sending credentials in cross origin requests, browsers expect the preflight response to contain the header `Access-Control-Allow-Credentials: true`.
According to [the fetch spec](https://fetch.spec.whatwg.org/#credentials), _"credentials are HTTP cookies, TLS client certificates, and authentication entries (for HTTP authentication)."_ From the mock service's point of view, whenever an OPTIONS request asks to include the "Cookie" or "Authorization" headers via `Access-Control-Request-Headers`, the consumer expects `Access-Control-Allow-Credentials` in the response.
This pull request simply always sets the header in preflight responses.
Drawbacks:
- Header is sent even when the browser does not expect it. The browsers I have met were tough and will be able to cope.
Alternatives would …

Always set 'Access-Control-Allow-Credentials: true' in preflight response

---

lib/pact/stub_service/cli.rb
tasks/package.rake

Easy one, fixes #100 
```
➜  pact-mock_service git:(feat/stubservicelog) ✗ pact-stub-service --help
Usage:
pact-stub-service PACT_URI ...
Options:
-p, [--port=PORT]            # Port on which to run the service
-h, [--host=HOST]            # Host on which to bind the service
-l, [--log=LOG]              # File to which to log output
[--log-level=LOG_LEVEL]  # Log level. Options are DEBUG INFO WARN ERROR
-o, [--cors=CORS]            # Support browser security in tests by responding to OPTIONS requests and adding CORS headers to mocked responses
[--ssl], [--no-ssl]      # Use a self-signed SSL cert to run the service over HTTPS
[--sslcert=SSLCERT]      # Specify the path to the SSL cert to use when running the service over HTTPS
[--sslkey=SSLKEY]        # Specify the path to the SSL key to …
```

feat: pact-stub-service log level cli opt

---

lib/pact/mock_service/request_handlers/interaction_replay.rb
spec/lib/pact/mock_service/request_handlers/interaction_replay_spec.rb

Do not pretty print a JSON object when serialization or serialization fail, for details see #103.

Improve logging robustness

---

.gitignore
lib/pact/consumer_contract/consumer_contract_decorator.rb
lib/pact/consumer_contract/interaction_decorator.rb
pact-mock_service.gemspec
spec/features/write_pact_file_spec.rb
spec/lib/pact/consumer_contract/consumer_contract_decorator_spec.rb

1) Added `metadata` to `InteractionDecorator`.
1) Changed `ConsumerContractDecorator#as_json` to use `ConsumerContract#writable_interactions`
See https://github.com/pact-foundation/pact-support/pull/75

Support not writing interactions to pact file if marked

---

.travis.yml

Show failures for example of 2.7 issues of gem
- Add 2.7.0 to TravisCI build matrix

CI: Add 2.7 to travis CI to show failures

---

spec/features/write_pact_file_spec.rb

Adding expectations to test https://github.com/pact-foundation/pact-mock_service/commit/67ef5a6b774eb56d082cef137af3ef91ed193b53 following the changes originally made in https://github.com/pact-foundation/pact-mock_service/pull/113

Add expectations to make sure "metadata: nil" isn't stored in the pact

---

lib/pact/consumer/mock_service/cors_origin_header_middleware.rb
spec/features/administration_endpoints_cors_spec.rb
spec/features/log/mock_multiple_responses_spec.log
spec/features/log/mock_one_response_spec.log
spec/features/mock_interactions_with_cors_spec.rb

Added 'Access-Control-Allow-Credentials' header to mock server responses when cors flag is enabled

Added 'Access-Control-Allow-Headers' = true to cors response headers

---

lib/pact/consumer/server.rb
lib/pact/mock_service/control_server/run.rb
lib/pact/mock_service/run.rb

Ruby 2.7 yields a warning if hash is passed as last argument but the method accepts keyword arguments. Fixed 3 cases with webrick options.

Fix Ruby 2.7 kwargs warning

---

lib/pact/mock_service/cli.rb
lib/pact/mock_service/cli/custom_thor.rb
lib/pact/mock_service/cli/pidfile.rb
pact-mock_service.gemspec

Thor `1.0` is out, and we're using it with Pact on https://github.com/department-of-veterans-affairs/vets-api.
But we're having to maintain a fork to do so. This PR bumps the Thor dependency with a `< 2.0` max, imitating recent versions of Railties.
Feedback is welcome. Thank you!

Update thor dependency

---

lib/pact/consumer/server.rb

In our testing, the host is not being passed when creating a new mock service. We were only ever able to create a server on localhost. This might fix the issue.

Allow Host to be configured

---

README.md

This updates an old link to be current
Also, the readme mentions the pact-dev google group - should that be slack?

Correct pact repo link

---

.github/workflows/release_gem.yml
.github/workflows/test.yml
lib/pact/consumer_contract/consumer_contract_writer.rb
pact-mock_service.gemspec
spec/features/log/mock_multiple_responses_spec.log

Noted, in the pact-ruby-standalone upgrade to Ruby 3.2, fixes that :)
```console
Writing pact for Provider to tmp/pacts/consumer-provider.json
ERROR ThreadError: can't be called from trap context\n\t/Users/saf/.rbenv/versions/3.2.2/lib/ruby/3.2.0/timeout.rb:132:in `synchronize'
INFO  going to shutdown ...
INFO  WEBrick::HTTPServer#start done.
```

fix: synchronize error when writing pact file, in Ruby 3.2.x

---

lib/pact/consumer/server.rb
lib/pact/mock_service/cli.rb
lib/pact/mock_service/request_handlers/interaction_post.rb
lib/pact/stub_service/cli.rb
pact-mock_service.gemspec
spec/integration/cli_spec.rb

This commit adds compatibility with Rack 3 and rack-test 2 while maintaining backwards compatibility.
Rack no longer depends on WEBrick since it's not a default gem in recent versions of Ruby, so add the Rackup gem to restore that functionality.
Use `read` instead of `string` to get the request body in a compatible way.
`spec/integration/cli_spec.rb` expected the pact files to get written before the server is shut down, whereas all the other similar specs, e.g. `spec/integration/control_server_cli_spec.rb`, shut the server down before expecting the files to be present. I'm not sure why exactly this works with Rack 2 but not Rack 3, or why it was just this one file that was different, but given all the other files follow the shut-down-the-server pattern, I changed this file to do the same. …

Add Rack 3 compatibility

---

.github/workflows/test.yml
lib/pact/consumer/mock_service/rack_request_helper.rb
lib/pact/consumer/server.rb
lib/pact/mock_service/control_server/run.rb
lib/pact/mock_service/run.rb
lib/rack/handler/webbrick.rb
pact-mock_service.gemspec

Fixes https://github.com/pact-foundation/pact-mock_service/issues/151
As of Rack > 3.1.0, the previous fixes for `Rack::Handler::WEBrick` not being found have been removed. Additionally, [`rack.input` is now optional](https://github.com/rack/rack/blob/b4c92944e0dd04874bed36281fc8e1a44023677f/CHANGELOG.md?plain=1#L40), so we can't guarantee the `body` variable is there when reading the request in the mock service.
I've also updated the CI to run with both Rack `2.x.x` and `3.x.x`, so we can guarantee backwards compatibility. I imagine if we stopped support for Rack `2.x.x` completely this would cause issues with dependencies for some users.

Fix Rack 3 support

---

.github/workflows/release_gem.yml

pact_broker-client, has a workflow for [gem-released](https://github.com/pact-foundation/pact_broker-client/tree/master/.github/workflows)
This triggers a [doc update](https://github.com/pact-foundation/pact_broker-client/blob/master/.github/workflows/trigger_pact_docs_update.yml) in docs.pact.io
I believe this isnt required as
- not in [deps](https://github.com/pact-foundation/pact_broker-client/blob/master/Gemfile#L10) or listed in [rubygems](https://rubygems.org/gems/pact_broker-client)
Apart from [`X_PACT_DEVELOPMENT`](https://github.com/pact-foundation/pact_broker-client/blob/master/Gemfile#L10)
Which should be updated to include `pact` which does in turn rely on `pact-mock_service`
And the docs from this readme are not currently synced to the docs.pact.io site

chore(ci): remove pact_broker client gem-released trigger

---

lib/pact/mock_service/cli.rb
lib/pact/stub_service/cli.rb
lib/rack/handler/webbrick.rb

use webbrick.rb custom handler in cli's
related to #152 
we get warnings when require'ing and using `Rack::Handler::WEBrick`. Removing this line removs teh warning, and tests all still pass
```console
lib/rack/handler/webbrick.rb:5: warning: already initialized constant Rack::Handler::WEBrick
.rbenv/versions/3.3.3/lib/ruby/gems/3.3.0/gems/rack-2.2.9/lib/rack/handler/webrick.rb:25: warning: previous definition of WEBrick was here
```

fix: rack 2.x dont load Rack::Handler::WEBrick class to avoid warnings
